### ISSUE TITLE
SELKS 4: IP address not obtained on boot.

### ISSUE THREAD

**Issue by jasonish** [StamusNetworks/SELKS#79] opened 2017-07-18 17:21 UTC
I installed into VirtualBox using pretty much default VirtualBox and SELKS option which gives me a single interface install. After boot, enp0s3 is up but does not have an IP address. If I do "ifdown enp0s3 && ifup enp0s3" it will get an address from the DHCP server (its nat'd right now, so the VirtualBox DHCP server) and all is good.

cat /etc/network/interfaces
```
# This file describes the network interfaces available on your system
# and how to activate them. For more information, see interfaces(5).

source /etc/network/interfaces.d/*

# The loopback network interface
auto lo
iface lo inet loopback

# The primary network interface
allow-hotplug enp0s3
iface enp0s3 inet dhcp
```

Same thing happens if I bridge the interface so my networks DHCP server is used.

For comparison, a default Debian 9 install in VirtualBox does get an IP address on boot.

**Comment by pevma** [comment] 2017-07-24 10:47
I've seen that too. The interesting part is that there is no network config change for that part that i can see of that will affect the default Debian behavior.

**Comment by b-u-g-s** [comment] 2017-07-27 11:09
Hi there,
The problem is because the management interface is set in promiscuous mode, and later during the boot process the following command is run: /sbin/dhclient -v -r interface
the "-r" (release) does not agree with an interface in promiscuous mode.

Furthermore, there is no need really for the management interface to be in promiscuous mode, only the monitoring interface should be.

Pevma pointed me to the /etc/network/if-up.d/idps-interface-tuneup_stamus script
on line 30 you are setting up promisc mode for all interfaces.

If you only do that for the monitoring interface, then the dhcp settings will work for the management interface.

In the mean time, users affected by this bug can:
- set a fixed ip address in /etc/network/interfaces
or
- run dhpclient networkinterface
(without the -r flag, and after the IP disappeared = ugly manual fix)

Hope this helps.
Cheers,
Bugs.

**Comment by b-u-g-s** [comment] 2017-07-28 10:53
Hi again,

Further testing and here is what I found:
- Disabling the line setting up interfaces in promisc mode in /etc/network/if-up.d/idps-interface-tuneup_stamus, does not fix the problem
- What breaks "dhcp", for me at least, is the /etc/rcx.d/S01wcid script which starts:
dhclient -v -r ensXXX
that "-r" breaks the DHCP process.

So to fix it, and because I do not have a wireless interface anyway on my test box, was to remove the /etc/init.d/wcid script.

Now the dhcp address sticks.

I also think the /etc/network/if-up.d/idps-interface-tuneup_stamus script is not working correctly, as it only sets the main interface in promisc mode (the one defined in /etc/network/interface)
The monitoring interface, does not appear in /etc/network/interface and is not set in promisc mode during boot.
Looks like it is screwing the monitoring process.

Running the /opt/selks/Scripts/Setup/setup-selks-ids-interface.sh
doesn't seem to fix the problem either.

Stoping and starting Suricata gives the following error in suricata.log
[12474] 28/7/2017 -- 11:32:45 - (tm-threads.c:2178) <Notice> (TmThreadWaitOnThreadInit) -- all 2 packet processing threads, 4 management threads initialized, engine started.
[12927] 28/7/2017 -- 11:32:45 - (source-af-packet.c:2002) <Error> (AFPCreateSocket) -- [ERRCODE: SC_ERR_AFP_CREATE(190)] - Couldn't set fanout mode, error Invalid argument
[12927] 28/7/2017 -- 11:32:45 - (source-af-packet.c:1395) <Error> (ReceiveAFPLoop) -- [ERRCODE: SC_ERR_AFP_CREATE(190)] - Couldn't init AF_PACKET socket, fatal error
[12474] 28/7/2017 -- 11:32:45 - (tm-threads.c:2097) <Error> (TmThreadCheckThreadState) -- [ERRCODE: SC_ERR_FATAL(171)] - thread W#01-ens192 failed

So, all the steps I needed to do for it to work are:
A. one off:
rename /etc/init.d/wcid to something else

B. After each reboot
service suricata stop
ip link set ens192 promisc on up
rm /vra/run/suricata.pid
service suricata start

note that the monitoring interface (ens192) needed to be set UP and in PROMISC mode manually.
somehow I also had to delete the /var/run/suricata.pid manually each time I wanted to restart the suricata service, so it looks there is a problem with shutting it down and up with the script/service.

With those steps I am able to keep my IDS IP address and get some alerts

hopes this help.

**Comment by pevma** [comment] 2017-07-28 14:27
It may be something else as well.
I removed the `/etc/network/if-up.d/idps-interface-tuneup_stamus` script

adjusted manually -    
```
# The primary network interface
auto enp0s3
allow-hotplug enp0s3
iface enp0s3 inet dhcp
```

cleared the `dmesg -C` - and got this upon reboot from dmesg (and no ip addr over dhcp):  
```
root@SELKS:~# dmesg |grep enp0s3
[    1.094503] e1000 0000:00:03.0 enp0s3: renamed from eth0
[   13.540768] IPv6: ADDRCONF(NETDEV_UP): enp0s3: link is not ready
[   13.545253] e1000: enp0s3 NIC Link is Up 1000 Mbps Full Duplex, Flow Control: RX
[   13.545557] IPv6: ADDRCONF(NETDEV_CHANGE): enp0s3: link becomes ready
[   46.355335] device enp0s3 entered promiscuous mode
```
So I just wonder why is it renaming `..enp0s3: renamed from eth0...` it should be just `enp0s3` without any renaming.

**Comment by pevma** [comment] 2017-07-28 14:32
Or maybe that renaming part is normal in Stretch?

**Comment by b-u-g-s** [comment] 2017-07-28 14:53
if you remove /etc/init.d/wcid you will get a dhcp address
in fact, you are getting one...
just try to ping you box whilst booting and you will see a response for a while (about 30s after full boot for me).
but then that wcid is calling dhcpclient -v -r interface_name 
and it removes the IP.
You can also try that dhcpclient -r command and you will see an error.

**Comment by pevma** [comment] 2017-07-31 11:00
I think i have found the issue.   
Even though `ifcofnig` is obsolete in Stretch - it seems it is still used in the network scripts (and included in Stretch dvd/iso downloads but not in `live`). If you install  -  `apt-get install net-tools` and after that reboot -  there is no issue and the interface comes up as expected.

**Comment by pevma** [comment] 2017-08-03 13:21
Fixed in branch `SELKS4-dev`

**Closed by pevma** 2017-08-03 13:21 UTC
