### ISSUE TITLE
Any ETA for SELKS 4.0?

### ISSUE THREAD

**Issue by Sc0th** [StamusNetworks/SELKS#67] opened 2017-04-19 12:51 UTC
Sorry - could not find a better place to ask!

**Comment by pevma** [comment] 2017-04-21 07:18
I hope in the next few days (if not today) to finalize that.
there is an upgrade script ready for th eSELKS3 to SELKS 4 upgrade - i need to finalize and test some additional SELKS packages.

**Comment by Sc0th** [comment] 2017-04-25 01:23
Excellent work, thank you!

have run through the script, couple of minor issues, after the upgrade i have a bunch of unassigned shards that will not clear in elasticsearch, may or may not be related. 

When i try to clear the elasticsearch data via the settings menu i get the following error 'Clearing failed: TransportError(400, u'illegal_argument_exception', u'request [/_stats/_search] contains unrecognized metric: [_search] -> did you mean [search]?')'

i will revert to backup this evening, happy to help test any future itterations.

**Comment by pevma** [comment] 2017-04-25 07:39
Thank you for the feedback! There will be some updates very soon to the upgrade script.

Would you please post a bug on the Scirius github (mentioning the 1.2.1 version) for the deletion issue with regards to ES 5?

With regards to - unassigned shards - can you reproduce that every time or?

**Comment by Sc0th** [comment] 2017-04-25 07:45
I will keep an eye open for the changes!

Bug posted.

Not sure, I will run through the procedure a couple more times, see if it occurs again.

One more (very minor) point, the update script in /opt/selks... needs a few tweaks after the upgrade.

**Comment by pevma** [comment] 2017-04-25 08:00
Thank you.
I am not entirely decided how is best to tackle the "default" upgrade scripts. Open to suggestions.
What where the tweaks needed?

**Comment by brandonmreeves** [comment] 2017-05-01 21:11
Is there an ISO for version 4 for a base install? Rather than upgrade, I would like to just do a clean install.

Thanks

**Comment by pevma** [comment] 2017-05-02 04:49
Hi,

It is upcoming - probably next week. We still have a few things/pkg details to clear up.
It would be awesome to receive some feedback on that install as well :)

**Comment by brandonmreeves** [comment] 2017-05-13 15:14
Great. I look forward to downloading, installing, and testing it. I seem to be having some of the same issues other are having with scirius (https://github.com/StamusNetworks/scirius/issues/104) with the migration to v4. So once the ISO is out, I will be glad to test it on a VM as well as a physical machine that we have here.

I have been involved in devops for a while and have experience with ES, django, php, and python so I look forward to contributing.

Please let me know i f there is anything else I can help with.

Thanks

**Comment by Sc0th** [comment] 2017-05-16 02:20
All gone rather quiet, anything I can help test?

**Comment by pevma** [comment] 2017-05-16 06:47
Seems quiet but I've been busy i think.

I will push a dev branch in a few min :) - so any feedback with plugging in the ES template would be appreciated for starters.

Note - it is a dev branch so things are moving...

**Comment by pevma** [comment] 2017-05-16 07:41
@invisiblethreat @brandonmreeves  - pushed a dev/test branch here for creating the SELKS 4 ISO  - https://github.com/StamusNetworks/SELKS/tree/SELKS4-dev  
Feedback is welcome (especially with the ES template) - please have in mind things are in dev/test condition however working :).

**Comment by Sc0th** [comment] 2017-05-17 00:46
Awesome! Will try to find some time to test this weekend.

**Comment by brandonmreeves** [comment] 2017-05-17 14:40
I have tested both the upgrade and iso build. There are a few minor issues but I figured out how to get past them. I created new issues with fixes. Will continue to do so unless you would like me to contribute differently.

**Comment by pevma** [comment] 2017-05-17 15:24
i just updated both the SELKS4-dev and master branches for the ISO and upgrade scripts respectively  - feedback is welcome.

**Comment by Sc0th** [comment] 2017-05-18 12:48
Update script seems to not like my install.....

Cloning into '/opt/selks/kibana4-dashboards'...
remote: Counting objects: 410, done.
remote: Compressing objects: 100% (7/7), done.
remote: Total 410 (delta 1), reused 0 (delta 0), pack-reused 403
Receiving objects: 100% (410/410), 93.04 KiB | 150.00 KiB/s, done.
Resolving deltas: 100% (333/333), done.
Checking connectivity... done.
Traceback (most recent call last):
  File "bin/manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/share/python/scirius/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 354, in execute_from_command_line
    utility.execute()
  File "/usr/share/python/scirius/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 346, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/share/python/scirius/local/lib/python2.7/site-packages/django/core/management/base.py", line 394, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/usr/share/python/scirius/local/lib/python2.7/site-packages/django/core/management/base.py", line 445, in execute
    output = self.handle(*args, **options)
  File "/usr/share/python/scirius/local/lib/python2.7/site-packages/rules/management/commands/kibana_reset.py", line 37, in handle
    self.kibana_reset()
  File "/usr/share/python/scirius/local/lib/python2.7/site-packages/rules/es_data.py", line 229, in kibana_reset
    self._create_kibana_mappings()
  File "/usr/share/python/scirius/local/lib/python2.7/site-packages/rules/es_data.py", line 147, in _create_kibana_mappings
    self.client.indices.create(index='.kibana',body={ "mappings": KIBANA_MAPPINGS })
  File "/usr/share/python/scirius/local/lib/python2.7/site-packages/elasticsearch/client/utils.py", line 73, in _wrapped
    return func(*args, params=params, **kwargs)
  File "/usr/share/python/scirius/local/lib/python2.7/site-packages/elasticsearch/client/indices.py", line 107, in create
    params=params, body=body)
  File "/usr/share/python/scirius/local/lib/python2.7/site-packages/elasticsearch/transport.py", line 318, in perform_request
    status, headers, data = connection.perform_request(method, url, params, body, ignore=ignore, timeout=timeout)
  File "/usr/share/python/scirius/local/lib/python2.7/site-packages/elasticsearch/connection/http_urllib3.py", line 128, in perform_request
    self._raise_error(response.status, raw_data)
  File "/usr/share/python/scirius/local/lib/python2.7/site-packages/elasticsearch/connection/base.py", line 124, in _raise_error
    raise HTTP_EXCEPTIONS.get(status_code, TransportError)(status_code, error_message, additional_info)
elasticsearch.exceptions.RequestError: TransportError(400, u'index_already_exists_exception', u'index [.kibana/s3hOkavtRUiIr8svmXGBdw] already exists')

**Comment by dgrgicevic** [comment] 2017-05-18 12:58
line 25  (service scirius stop)  should be  "supervisorctl scirius stop" 
line 260 ( rm /opt/selks/kibana4-dashboards/* -r )   should be  "rm -rf /opt/selks/kibana4-dashboards"  otherwise  .git is  remaining  

line 263  before  executing,  ( # Re-upload the new ones
cd /usr/share/python/scirius/ && \
source bin/activate
python bin/manage.py kibana_reset.
deactivate )

kibana  should  run   ( systemctl start kibana )

**Comment by Sc0th** [comment] 2017-05-19 00:06
Also the following is being kicked out from the delete indices cron run -

Subject: Cron <root@tower> /usr/local/bin/curator delete indices --older-than 16 --time-unit days --timestring '%Y.%m.%d'
To: <root@xx.xx.xx>

2017-05-19 03:00:04,757 INFO      Job starting: delete indices
2017-05-19 03:00:04,766 ERROR     Expected Elasticsearch version range > 1.0.0 < 3.0.0
2017-05-19 03:00:04,766 ERROR     Incompatible with version 5.4.0 of Elasticsearch

**Comment by pevma** [comment] 2017-05-19 07:35
Thanks for the input guys !
I just p pushed some fixes to the master that address :
- the old cronjob removal 
- proper removal of the old dashboard repo 
- kernel upgrade

@dgrgicevic  
- works fine I think and as it will be replaced (as this is the older Scirius) - it should be ok.
- second point - why does Kibana needs to e running during the dashboard upload. We only need ES running?

**Comment by dgrgicevic** [comment] 2017-05-19 08:26
@pevma 
thx, second point,  if  kibana  did  not  run, i   got  the  same mistake  as @Sc0th 
additional,  i  have issue with  evebox  accessing  reports/netflow   there is in  elasticsearch log  
"org.elasticsearch.transport.RemoteTransportException: [host][x.x.x.x:9300][indices:data/read/search[phase/query]]
Caused by: org.elasticsearch.index.query.QueryShardException: No mapping found for [netflow.bytes] in order to sort on"
and evebox/reports/flow  
"org.elasticsearch.transport.RemoteTransportException: [host][x.x.x.x:9300][indices:data/read/search[phase/query]]
Caused by: org.elasticsearch.index.query.QueryShardException: No mapping found for [flow.age] in order to sort on"

**Comment by pevma** [comment] 2017-05-19 10:41
@dgrgicevic  - ok second point is fixed in gitmaster.
Can you describe a bit more please how can the evebox problem be reproduced?

**Comment by dgrgicevic** [comment] 2017-05-19 11:18
@pevma -   thx   for  the  great  product  first  :)   i  have  the  same issue on  2  different  systems after  update  to  4 and  EveBox Version 0.7.0 (rev 8ef8639)  
where in source from evebox  "webapp/src/app/reports/netflow-report.component.ts"  is  definition
params.sortBy = 'netflow.bytes';
field: 'netflow.bytes'
field: 'netflow.bytes'
and 
"webapp/src/app/pipes/eventdescription.pipe.ts: "   + `; Bytes: ${netflow.bytes}` 

there is  no  such  field  in logstash-flow-*    only  flow*    no  netflow*

**Comment by rcfontana** [comment] 2017-05-19 11:20
Is there a .ISO ready for download ? I'm getting some failures with
live-build.

Thanks!

**Comment by pevma** [comment] 2017-05-19 11:37
@rcfontana which repo are you using? If you are building from scratch SELKS4 you can test the dev branch [SELKS4-dev]( https://github.com/StamusNetworks/SELKS/tree/SELKS4-dev)  branch.  

@dgrgicevic  - can you please post a bug on the [EveBox](https://github.com/jasonish/evebox) github and keep us posted. I will try to reproduce.

**Comment by dgrgicevic** [comment] 2017-05-22 06:05
@pevma ,  still  searching  for solution,  meanwhile i  tested  latest 3-4update  script,  it  works  fine, only  somewhere  on  the  end  before  #reboot it  should be  executed "systemctl daemon-reload" and "systemctl enable logstash"  otherwise  logstash  stays in  disabled  mode.

**Comment by pevma** [comment] 2017-05-23 09:11
Latest changes are pushed to the upgrade script.  I think it looks "final" :)

**Comment by dgrgicevic** [comment] 2017-05-23 09:17
@pevma  check  a  typo  in 
KTS5/dashboards/index-pattern/logstash-alert-*.json
on the  end  it is  written "title":"logstash-tls-*"} but  it  should  be "title":"logstash-alert-*"} if i am  not mistaken

**Comment by pevma** [comment] 2017-06-07 16:20
After a bit of testing and feedback it seems most is ready however I am getting some mixed results in the dashboards where we have top dest/src IPs - Like inn the alerts dashboard. Anyone noticed that or being able to reproduce it?

**Comment by brandonmreeves** [comment] 2017-06-07 16:39
Havent had any issue with dashboards. My only issue is with the system settings where I need to clear ES data. I receive an error that was posted on the scirius github page. Otherwise all seems to work fine. I have tested both the upgrade script and the ISO on virtual and physical systems.

**Comment by pevma** [comment] 2017-06-07 16:47
@brandonmreeves  great to hear -  the ISO created from the selks4-dev branch right? Thanks!

**Comment by brandonmreeves** [comment] 2017-06-07 16:53
yes.

**Comment by pevma** [comment] 2017-06-07 23:09
Great to hear!

**Comment by pevma** [comment] 2017-06-08 12:44
I think if there are no major bugs uncovered last minute -  we should be all set for beta/rc release early next week.

**Comment by brandonmreeves** [comment] 2017-06-08 21:57
Awesome. Do you have any idea about the issue in scirius? Not being able to delete data might be a big deal if someone cant get to the command line and run the curl commands locally. This is the issue I am referencing

https://github.com/StamusNetworks/scirius/issues/104

**Comment by Sc0th** [comment] 2017-06-09 02:58
It's a no go for me until the issue with Scirius is fixed, I am waiting with hopeful anticipation.

**Comment by pevma** [comment] 2017-06-09 09:50
This issue is fixed in the next Scirius CE version. So you may just need a simple update to the new package when available - hopefully next week.

If you need to delete all ES data it can be done from shell too - [here is an example](https://github.com/StamusNetworks/SELKS/blob/master/scripts/SELKS3-SELKS4-test/SN-S3-S4-Upgrade.sh#L385) - you just need to change the `unit_count` in terms of older than the number of days

**Comment by pevma** [comment] 2017-06-09 20:26
I have something that I am chasing  - on a brand new ISO install (from the selks4-dev branch) on the Alerts dashboard the top src and top dst IP visualization do not display - they only show "0". Can anyone confirm that?

**Comment by brandonmreeves** [comment] 2017-06-10 01:17
Thats odd.  Im not experiencing that. Maybe we can solve this.

Peter can you build an ISO or make one just like you are using and make it downloadable for me somewhere? Ill use it to install in a test environment to see if I get similar results.

**Comment by pevma** [comment] 2017-06-10 09:48
I think you can reproduce it like following: 

```
git clone https://github.com/StamusNetworks/SELKS.git
git checkout SELKS4-dev
./build-debian-live.sh
```

It will take probably 30-40 min and you should end up with the `SELKS.iso` under the `Stamus-Live-Build` folder.

**Comment by dgrgicevic** [comment] 2017-06-10 12:08
@pevma 

Well,  created/installed SELKS4-DEV

Issues:

elastic search at start yellow:
easy  fix:

curl -XPUT 'localhost:9200/_settings' -d '{
    "index" : {
        "number_of_replicas" : 0
    }
}'


suricata:  
selks4-addin.yaml

netflow  enabled, dnp3 disabled

suricata  updates: 
not  working.

Fix via cron:

kibana/elasticsearch

1:
 SN FILE-Transactions 
 Visualize: agg.schema is undefined
error in  kibana


Refreshing Index in Kibana:

Could not locate that index-pattern-field (id: dest_ip.raw)
Could not locate that index-pattern-field (id: src_ip.raw)


the  same  is  visible  in 


Dashboard
SN ALERTS

after  refreshing  index 

2:

evebox -> Reports ->  Flow
error  in  elasticsearch.log

 org.elasticsearch.transport.RemoteTransportException: [2uQFBV1][127.0.0.1:9300][indices:data/read/search[phase/query]]
Caused by: org.elasticsearch.index.query.QueryShardException: No mapping found for [flow.age] in order to sort on

evebox -> Reports -> NetFlow
error  in  elasticsearch.log, timestamp for netflow logs  remain  the  same

org.elasticsearch.transport.RemoteTransportException: [8sgZrTj][127.0.0.1:9300][indices:data/read/search[phase/query]]
Caused by: org.elasticsearch.index.query.QueryShardException: No mapping found for [netflow.pkts] in order to sort on

org.elasticsearch.transport.RemoteTransportException: [8sgZrTj][127.0.0.1:9300][indices:data/read/search[phase/query]]
Caused by: org.elasticsearch.index.query.QueryShardException: No mapping found for [netflow.bytes] in order to sort on

Refreshing Index in Kibana:
logstash-snmp:


No matching indices found: [index_not_found_exception] no such index, with { resource.type="index_or_alias" & resource.id="logstash-smtp-" & index_uuid="na" & index="logstash-smtp-" }

**Comment by jasonish** [comment] 2017-06-10 13:51
The no mapping errors for flow.age, netflow.pkts and netflow.bytes created by the EveBox queries will be fixed in a new release of EveBox. From what I can tell, the queries still generate correct data, and those errors don't actually affect the result, or ripple back to the client. But I do have a way to clear there up.

**Comment by pevma** [comment] 2017-06-10 14:21
@dgrgicevic - excellent feedback! Thank you. 

With regards to 

1. Yes noticed that too. Those are the Kibana indexes that are replicating and getting the tallow status for ES in Scirius

2. I will look at the selks4-addin.yaml to make sure those are enabled.

3. How do you mean Suricata is not upgrading?

4. I didn't understand the "fix via cron "? Could you please expand :)

5. Yes - those dashboards show the errors for me too. Wondering the best approach of fixing this in mind with backword comparability.Open to suggestions...

**Comment by dgrgicevic** [comment] 2017-06-10 20:47
@pevma    
updating suricata  rules,  not  upgrading..  :)    i noticed  that rules  are  not updating overnight, why ?  did not  having  time  to  investigate  this..   just  crated crontab  to fix  this  task

**Comment by pevma** [comment] 2017-06-11 09:20
@dgrgicevic   - the correct time zone is set on the OS and on Scirius ? I tried it manually (as in the cronjob itself) and it works here.

Those dashboards (Files/Alerts) seemed ok in ELK 5.4.0 ...now with 5.4.1 they seem to err like that above - need to investigate... open to ideas too.

**Comment by dgrgicevic** [comment] 2017-06-11 21:33
@pevma the  timezone is  correct,  i  left  test  VM  running and  there is  no  auto update of  suricata rules. It  has  nothing to  do  with  ELK  5.4.x   as  the  date  of  scirius.rules in /etc/suricata/rules has not  be changed,  Manual  update (Suricata Ruleset Actions)  in Scirius  works  fine.

**Comment by pevma** [comment] 2017-06-12 12:43
@dgrgicevic  - The ELK 5.4 dashboards comment was separate. ok so if i understand correctly the rule update cronjob is not kicking in ?

**Comment by dgrgicevic** [comment] 2017-06-12 14:22
@pevma correct,   New  VM,  no  changes except OS update,  and  interface  configuration (NIC),  after 24h   there  was  no  update of  suricata  rules,  Time  zone is  set  correct in OS  and Scirius.

**Comment by pevma** [comment] 2017-06-14 06:52
Trying to reproduce...

**Comment by dgrgicevic** [comment] 2017-06-14 07:23
@pevma thx,  also confirm  the  same issue  with  suricata  (util-mpm-hs.c:942) <Error> (SCHSSearch) -- [ERRCODE: SC_ERR_FATAL(171)] - Hyperscan returned error -1)  but i  saw  you  already  reacted

**Comment by pevma** [comment] 2017-06-14 07:29
@dgrgicevic  - thank you. Please keep those issue separate :) with the redmine tracker for Suricata.

**Comment by Sc0th** [comment] 2017-06-14 12:43
Been around the upgrade loop twice today, both times this happens, any ideas?

root@tower:~# curl -s 'localhost:9200/_cat/shards?v' | grep -i unas
logstash-smtp-2017.06.14     1     r      UNASSIGNED                          
logstash-smtp-2017.06.14     3     r      UNASSIGNED                          
logstash-smtp-2017.06.14     4     r      UNASSIGNED                          
logstash-smtp-2017.06.14     2     r      UNASSIGNED                          
logstash-smtp-2017.06.14     0     r      UNASSIGNED                          

I can clear them with 

root@tower:~# curl -XDELETE 'localhost:9200/logstash-smtp-2017.06.14/'

But they soon come back....

**Comment by pevma** [comment] 2017-06-14 13:01
it think this might help? (as @dgrgicevic suggested) - 
```
curl -XPUT 'localhost:9200/_settings' -d '{
"index" : {
"number_of_replicas" : 0
}
}'
```

**Comment by Sc0th** [comment] 2017-06-14 23:54
Ran the above last night, this morning the 5 unassigned shards are back, so no joy.

I also noticed that the 2am rules update did not take place, system was built from 3->4 using the upgrade script.

**Comment by Sc0th** [comment] 2017-06-15 00:27
ok, so the 2am is a simple fix, the switch to www-root by the cron job changes shell to sh the job then calls source which is a ksh thing, so replacing source with a period which does the same thing in sh makes the problem go away, thus:

in /etc/crontab

www-data ( cd /usr/share/python/scirius/ && source bin/activate && python bin/manage.py updatesuricata && deactivate )

nees to be:

www-data ( cd /usr/share/python/scirius/ && . bin/activate && python bin/manage.py updatesuricata && deactivate )

**Comment by Sc0th** [comment] 2017-06-15 07:19
FWIW - this is what I see in the logs when the 5 unassigned shards reappear, means bagger all to me!

`2017-06-14T08:16:15+08:00 tower elasticsearch[740]: MapperParsingException[Field name [smtp.anomaly.count] cannot contain '.']

2017-06-14T08:16:15+08:00 tower elasticsearch[740]: [2017-06-14 08:16:15,412][DEBUG][action.bulk              ] [Haywire] [logstash-alert-2017.06.14][3] failed to execute bulk item (index) index {[logstash-alert-2017.06.14][SELKS][AVyj9TYanSoqlpypC-0W], source[{"timestamp":"2017-06-14T08:16:13.973404+0800","flow_id":193112471377925,"in_iface":"eth0","event_type":"alert","src_ip":"192.168.xx.xx","src_port":25,"dest_ip":"223.84.xx.xx","dest_port":56799,"proto":"TCP","tx_id":0,"alert":{"action":"allowed","gid":1,"signature_id":2220006,"rev":1,"signature":"SURICATA SMTP no server welcome message","category":"Generic Protocol Command Decode","severity":3},"smtp":{"helo":"*.*"},"vars":{"flowints":{"smtp.anomaly.count":1}},"payload":"","payload_printable":"","stream":1,"packet":"AB2q2qsoAFBWpncrCABFAAAoKGRAAEAGabnAqDyq31TMCwAZ3d8zZOxLLuVdOVAQOQhEUgAAAAAAAAAA","packet_info":{"linktype":1},"@version":"1","@timestamp":"2017-06-14T00:16:13.973Z","path":"/var/log/suricata/eve.json","host":"tower.scothular.co.uk","type":"SELKS","src_ip4":"192.168.xx.xx","geoip":{"ip":"223.84.204.11","country_code2":"CN","country_code3":"CHN","country_name":"China","continent_code":"AS","region_name":"22","city_name":"Beijing","latitude":39.9289,"longitude":116.38830000000002,"timezone":"Asia/Harbin","real_region_name":"Beijing","location":[116.38830000000002,39.9289],"coordinates":[116.38830000000002,39.9289]},"dest_ip4":"223.84.xx.xx"}]}

**Comment by pevma** [comment] 2017-06-15 13:12
@Sc0th - very well spotted on the cronjob :+1:  ! The funny thing is i had that fix in the Kibana dashboards package but didn't port it to the cronjob  - fixed in master and the dev github branch.

about the unassigned shards - that err info might be helpful. What is the output of - 
```
curl -XGET 'localhost:9200/_cat/shards?h=index,shard,prirep,state,unassigned.reason&pretty' |grep UNASSIGNED
```

**Comment by pevma** [comment] 2017-06-15 13:33
So basically the ES error you posted above is [explained here](https://discuss.elastic.co/t/field-name-cannot-contain/33251/12) and thif that should work is the ruby filter code that needs to be added to the `/etc/logstash/conf.d/logstash.conf` but ES5 compatible. Similar to the [ruby block here](https://github.com/StamusNetworks/SELKS/blob/master/scripts/SELKS3-SELKS4-test/SN-S3-S4-Upgrade.sh#L179) to avoid such situations we need to add:  

```
  ruby {
        code => "
          event.to_hash.keys.each { |k| event[ k.sub('.','_') ] = event.remove(k) if k.include?'.' }
        "
    }  
```

I would suggest -  clean up the "unassigned" shards , add the code and restart logstash (watch out if any related errors to that code might appear in `/var/log/logstash/logstash-plain.log`) Let us know if the problem appears again.

**Comment by brandonmreeves** [comment] 2017-06-27 23:11
Any new updated on v4 release?

**Comment by pevma** [comment] 2017-06-30 14:15
Hey there!
Stretch was out a day ago so we are including that as well :).
I have  a working test repo that iIneed to clean up and will be making public over the next cpl of days for some much appreciated feedback.

**Comment by pevma** [comment] 2017-08-22 13:23
ETA has arrived for v4 release :) 
[SELKS 4 is out](https://www.stamus-networks.com/2017/08/22/selks-4-0/)

**Closed by pevma** 2017-08-22 13:23 UTC
